# Stage 1
FROM node:16 AS build

WORKDIR /app
COPY ./frontend/docker-app/package*.json ./
RUN npm install
COPY ./frontend/docker-app ./
RUN npm run build

# Stage 2
FROM nginx:alpine
COPY ./frontend/docker-app/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
