# Stage 1
FROM node:16 AS build

WORKDIR /app
COPY ./backend/package.json ./backend/package-lock.json ./
RUN npm install
RUN npm install cors

COPY ./backend ./

# Stage 2
FROM node:16-alpine

WORKDIR /app
COPY --from=build /app /app
EXPOSE 5000
CMD ["node", "server.js"]
